version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: api
      MYSQL_PASSWORD: api
      MYSQL_DATABASE: expenseshare_api
    ports:
      - "3306:3306"
  ###< doctrine/doctrine-bundle ###
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###